[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
# Alt + B (Move backward one word)
key = "B"
mods = "Alt"
chars = "\u001BB"
[[keyboard.bindings]]
# Alt + F (Move forward one word)
key = "F"
mods = "Alt"
chars = "\u001BF"
[[keyboard.bindings]]
# Alt + D (Delete the word after the cursor)
key = "D"
mods = "Alt"
chars = "\u001BD"
[[keyboard.bindings]]
# Alt + Backspace (Delete word before cursor)
key = "Backspace"
mods = "Alt"
chars = "\u001B\u007F"
[[keyboard.bindings]]
# Alt + U (Uppercase from cursor to end of word)
key = "U"
mods = "Alt"
chars = "\u001BU"
[[keyboard.bindings]]
# Alt + L (Lowercase from cursor to end of word)
key = "L"
mods = "Alt"
chars = "\u001BL"
[[keyboard.bindings]]
# Alt + C (Capitalize the current word)
key = "C"
mods = "Alt"
chars = "\u001BC"
[[keyboard.bindings]]
# Alt + . (Insert the last argument of previous command)
key = "."
mods = "Alt"
chars = "\u001B."
[[keyboard.bindings]]
# Alt + Y (Yank the top of the kill-ring)
key = "Y"
mods = "Alt"
chars = "\u001BY"
[[keyboard.bindings]]
# Alt + / (Attempt completion)
key = "/"
mods = "Alt"
chars = "\u001B/"
[[keyboard.bindings]]
# Alt + T (Transpose the words around cursor)
key = "T"
mods = "Alt"
chars = "\u001BT"
[[keyboard.bindings]]
# Alt + R (Recall the last command that matches input)
key = "R"
mods = "Alt"
chars = "\u001BR"
[[keyboard.bindings]]
# Alt + N (Search forward through history)
key = "N"
mods = "Alt"
chars = "\u001BN"
[[keyboard.bindings]]
# Alt + P (Search backward through history)
key = "P"
mods = "Alt"
chars = "\u001BP"
[[keyboard.bindings]]
# Alt + Q (Not a standard bash shortcut, customizable)
key = "Q"
mods = "Alt"
chars = "\u001BQ"
